### ISSUE TITLE
OSMPbfLoader fails on Windows 10/11

### ISSUE THREAD

**Issue by ca9071jp2** [kraina-ai/srai#390]
When running OSMPbfLoader on Windows,  the code fails with the following error message, seemingly due to trying to copy the pbf file from a temporary folder that doesnt exist. This is regardless of whether the download_directory parameter is set or not (which should fix the error in theory). A sort of hot-fix is to first run the command with download_directory="." (current working dir), and then after it has downloaded and failed then set the pbf_file to the name of the file downloaded:

`KeyError                                  Traceback (most recent call last)
File ~\anaconda3\envs\srai\lib\site-packages\srai\loaders\osm_loaders\pbf_file_downloader.py:278, in PbfFileDownloader._download_pbf_file_for_polygon_from_protomaps(self, polygon, region_id, polygon_id)
    277 try:
--> 278     extraction_uuid = start_extract_result["uuid"]
    279     status_check_url = start_extract_result["url"]

KeyError: 'uuid'

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
File ~\anaconda3\envs\srai\lib\site-packages\srai\loaders\osm_loaders\pbf_file_downloader.py:146, in PbfFileDownloader.download_pbf_files_for_regions_gdf(self, regions_gdf)
    145 if self.download_source == "protomaps":
--> 146     regions_mapping = self._download_pbf_files_for_polygons_from_protomaps(regions_gdf)
    147 elif self.download_source in PbfSourceExtractsFunctions:

File ~\anaconda3\envs\srai\lib\site-packages\srai\loaders\osm_loaders\pbf_file_downloader.py:212, in PbfFileDownloader._download_pbf_files_for_polygons_from_protomaps(self, regions_gdf)
    211     polygons = flatten_geometry(row.geometry)
--> 212     regions_mapping[region_id] = [
    213         self._download_pbf_file_for_polygon_from_protomaps(
    214             polygon, region_id, polygon_id + 1
    215         )
    216         for polygon_id, polygon in enumerate(polygons)
    217     ]
    219 return regions_mapping

File ~\anaconda3\envs\srai\lib\site-packages\srai\loaders\osm_loaders\pbf_file_downloader.py:213, in <listcomp>(.0)
    211     polygons = flatten_geometry(row.geometry)
    212     regions_mapping[region_id] = [
--> 213         self._download_pbf_file_for_polygon_from_protomaps(
    214             polygon, region_id, polygon_id + 1
    215         )
    216         for polygon_id, polygon in enumerate(polygons)
    217     ]
    219 return regions_mapping

File ~\anaconda3\envs\srai\lib\site-packages\srai\loaders\osm_loaders\pbf_file_downloader.py:284, in PbfFileDownloader._download_pbf_file_for_polygon_from_protomaps(self, polygon, region_id, polygon_id)
    281     error_message = (
    282         f"Error from the 'Protomaps' service: {json.dumps(start_extract_result)}."
    283     )
--> 284     raise RuntimeError(error_message) from err
    286 with tqdm() as pbar:

RuntimeError: Error from the 'Protomaps' service: {"errors": "Please wait a bit - you are rate limited to 18 extracts per hour."}.

During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)
Cell In[16], line 21
     17 # loader = OSMPbfLoader(pbf_file="denmark.osm.pbf")
     19 loader = OSMPbfLoader(download_directory=".")
---> 21 features = loader.load(area, tags, )
     23 features.head(3)

File ~\anaconda3\envs\srai\lib\site-packages\srai\loaders\osm_loaders\osm_pbf_loader.py:111, in OSMPbfLoader.load(self, area, tags)
    109     downloaded_pbf_files = {Path(self.pbf_file).name: [self.pbf_file]}
    110 else:
--> 111     downloaded_pbf_files = PbfFileDownloader(
    112         download_source=self.download_source,
    113         download_directory=self.download_directory,
    114         switch_to_geofabrik_on_error=self.switch_to_geofabrik_on_error,
    115     ).download_pbf_files_for_regions_gdf(regions_gdf=area_wgs84)
    117 merged_tags = self._merge_osm_tags_filter(tags)
    119 pbf_handler = PbfFileHandler(tags=merged_tags)

File ~\anaconda3\envs\srai\lib\site-packages\srai\loaders\osm_loaders\pbf_file_downloader.py:157, in PbfFileDownloader.download_pbf_files_for_regions_gdf(self, regions_gdf)
    152 if self.download_source != "geofabrik" and self.switch_to_geofabrik_on_error:
    153     warnings.warn(
    154         f"Error occured ({err}). Auto-switching to 'geofabrik' download source.",
    155         stacklevel=1,
    156     )
--> 157     regions_mapping = self._download_pbf_files_for_polygons_from_existing_extracts(
    158         regions_gdf, override_to_geofabrik=True
    159     )
    160 else:
    161     error_message = str(err)

File ~\anaconda3\envs\srai\lib\site-packages\srai\loaders\osm_loaders\pbf_file_downloader.py:199, in PbfFileDownloader._download_pbf_files_for_polygons_from_existing_extracts(self, regions_gdf, override_to_geofabrik)
    197 for region_id, row in regions_gdf.iterrows():
    198     polygons = flatten_geometry(row.geometry)
--> 199     regions_mapping[region_id] = [
    200         self.clipper.clip_pbf_file(polygon, downloaded_pbf_files) for polygon in polygons
    201     ]
    203 return regions_mapping

File ~\anaconda3\envs\srai\lib\site-packages\srai\loaders\osm_loaders\pbf_file_downloader.py:200, in <listcomp>(.0)
    197 for region_id, row in regions_gdf.iterrows():
    198     polygons = flatten_geometry(row.geometry)
    199     regions_mapping[region_id] = [
--> 200         self.clipper.clip_pbf_file(polygon, downloaded_pbf_files) for polygon in polygons
    201     ]
    203 return regions_mapping

File ~\anaconda3\envs\srai\lib\site-packages\srai\loaders\osm_loaders\pbf_file_clipper.py:138, in PbfFileClipper.clip_pbf_file(self, geometry, pbf_files)
    136         self._convert_o5m_to_pbf(clipped_pbf_files_list[0], final_osm_path)
    137     else:
--> 138         shutil.copy(clipped_pbf_files_list[0], final_osm_path)
    139 # merge all of the files and copy it
    140 else:
    141     merge_function(clipped_pbf_files_list, final_osm_path_alphanumeric_safe)

File ~\anaconda3\envs\srai\lib\shutil.py:417, in copy(src, dst, follow_symlinks)
    415 if os.path.isdir(dst):
    416     dst = os.path.join(dst, os.path.basename(src))
--> 417 copyfile(src, dst, follow_symlinks=follow_symlinks)
    418 copymode(src, dst, follow_symlinks=follow_symlinks)
    419 return dst

File ~\anaconda3\envs\srai\lib\shutil.py:254, in copyfile(src, dst, follow_symlinks)
    252     os.symlink(os.readlink(src), dst)
    253 else:
--> 254     with open(src, 'rb') as fsrc:
    255         try:
    256             with open(dst, 'wb') as fdst:
    257                 # macOS

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/user/AppData/Local/Temp/tmpyney0pr_/pbf_files/denmark_b40f02fb6ddb14cd92ceea1b5bd27c2a7fbeb4c37c818338f760f8f34a293528.osm.pbf'`

**Comment by RaczeQ** [comment]
Thanks for submitting this issue and providing a full stack trace!

I think the issue is a permissions error while executing code. In one operation, where PBF file clipping is executed, we work in a temporary directory using `tempfile.TemporaryDirectory`. By default, it looks for the temporary directory in the OS (/tmp for UNIX and the equivalent for Windows). To mitigate it, we changed the `TemporaryDirectory` to be created in the same working directory as the executed code to hopefully allow the code to work without jumping between disks or partitions.

You can see full changes in this PR #391 and we released a 0.5.2 version with this fix.

**Comment by simonusher** [comment]
After some investigation, it seems that the sequence of events that leads to the error is:
1. Protomaps rate limit - `RuntimeError: Error from the 'Protomaps' service: {"errors": "Please wait a bit - you are rate limited to 18 extracts per hour."}.`
2. Fallback to geofabrik - `Error occured ({err}). Auto-switching to 'geofabrik' download source."`
3. `clip_pbf_file` method of `PbfFileClipper` used with [Osmosis](https://wiki.openstreetmap.org/wiki/Osmosis)
4. Osmosis failing silently due to not finding the Java runtime which is required [[source](https://wiki.openstreetmap.org/wiki/Osmosis/Quick_Install_(Windows)#:~:text=You%20need%20Java%20(specifically%20Java%20Runtime%20Environment)%20to%20be%20able%20to%20run%20osmosis)].
5. The expected output file of Osmosis not being there - it failed, didn't produce the output so it's not there.

I would say the course of actions should be:
Decide if this part is necessary for delivering the functionality (downloading pbfs for areas),
1. Yes - are there any alternatives to osmosis?
1.1 Yes - use them instead.
1.2 No (I really don't like this tree branch)
                - Make sure the error is not silent - capture the output from osmosis, notify the user what the actual problem is.
                - Tell the users that in this specific case (MacOS, Windows, protomaps failing etc.) they might need the java runtime to support the functionality
2. No - great, remove it. Problem solved, possibly at some cost.

If we used pyogrio or other library for reading pbfs, maybe this wouldn't be needed at all, as you can filter the records by geometry - [example in pyogrio](https://pyogrio.readthedocs.io/en/latest/introduction.html#filter-records-by-spatial-extent)

**Comment by Calychas** [comment]
This should be resolved as of 0.7.0 as we are not using protomaps anymore
