### ISSUE TITLE
Tutorial notebook 6 fails with Exception: Could not deserialize ATN with version  (expected 4).

### ISSUE THREAD

**Issue by pmallas** [kraina-ai/srai#434]
Hello,

Running notebook 6 from the answers directory yields this error:

```
portugal_embeddings = geovex_embedder.fit_transform(
    buffered_regions,
    portugal_features,
    portugal_joint_features,
    portugal_h3_neighbourhood,
    trainer_kwargs={
        "max_epochs": 5,
        "accelerator": (
            "cpu" if torch.backends.mps.is_available() else "auto"
        ),  # GeoVexEmbedder does not support MPS
    },
)
```

with Error:

```
File [~\Miniconda3\envs\ais\lib\site-packages\antlr4\atn\ATNDeserializer.py:50](http://localhost:8891/lab/tree/~/Miniconda3/envs/ais/lib/site-packages/antlr4/atn/ATNDeserializer.py#line=49), in ATNDeserializer.checkVersion(self)
     48 version = self.readInt()
     49 if version != SERIALIZED_VERSION:
---> 50     raise Exception("Could not deserialize ATN with version " + str(version) + " (expected " + str(SERIALIZED_VERSION) + ").")

Exception: Could not deserialize ATN with version  (expected 4).
```

**Comment by simonusher** [comment]
Hi @pmallas. Thank you for reporting that. I'll look into it

**Comment by simonusher** [comment]
Okay so I've got two things:

1. I pushed some fixes to the `main` branch, some of which were related to notebook 6. They look mostly unrelated to your problem though. The notebook wasn't completely polished, since we hadn't finished it in time for the in-person tutorial and ended up not using it. Regardless, it shouldn't hang in an unusable state so I made some changes.
2. I wasn't able to reproduce your error unfortunately.
- I normally use standard venvs, not conda so I started with that and were able to go through the notebook without an error.
- I then tried to create a conda env and run a notebook that way. Still no error.
What I did:
```bash
conda create -n srai-tutorial python=3.10
conda activate srai-tutorial
pip install -r requirements.txt
jupyter notebook
```
and run all cells.
Would you be able to pull the latest version, create a fresh env and see if you still face the error?
If not, please provide some more information on your environment (python version, pip freeze output) so it's easier to track down the issue.

**Comment by simonusher** [comment]
I'm glad to here that! 😄
